/**
* @description redux action types for 4 types of reducers
*/

//Auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

//Item 
export const ITEM_CREATE_SUCCESS = "ITEM_CREATE_SUCCESS";
export const ITEM_CREATE_FAIL = "ITEM_CREATE_FAIL";
export const ITEM_GETALL_SUCCESS = "ITEM_GETALL_SUCCESS";
export const ITEM_GETALL_FAIL = "ITEM_GETALL_FAIL";
export const ITEM_GETSPEC_SUCCESS = "ITEM_GETSPEC_SUCCESS";
export const ITEM_GETSPEC_FAIL = "ITEM_GETSPEC_FAIL";
export const ITEM_UPDATE_SUCCESS = "ITEM_UPDATE_SUCCESS";
export const ITEM_UPDATE_FAIL = "ITEM_UPDATE_FAIL";
export const ITEM_DELETE_SUCCESS = "ITEM_DELETE_SUCCESS";
export const ITEM_DELETE_FAIL = "ITEM_DELETE_FAIL";


//Customer
export const CUSTOMER_CREATE_SUCCESS = "CUSTOMER_CREATE_SUCCESS";
export const CUSTOMER_CREATE_FAIL = "CUSTOMER_CREATE_FAIL";
export const CUSTOMER_GETALL_SUCCESS = "CUSTOMER_GETALL_SUCCESS";
export const CUSTOMER_GETALL_FAIL = "CUSTOMER_GETALL_FAIL";
export const CUSTOMER_GETSPEC_SUCCESS = "CUSTOMER_GETALL_SUCCESS";
export const CUSTOMER_GETSPEC_FAIL = "CUSTOMER_GETSPEC_FAIL";
export const CUSTOMER_UPDATE_SUCCESS = "CUSTOMER_UPDATE_SUCCESS";
export const CUSTOMER_UPDATE_FAIL = "CUSTOMER_UPDATE_FAIL";
export const CUSTOMER_DELETE_SUCCESS = "CUSTOMER_DELETE_SUCCESS";
export const CUSTOMER_DELETE_FAIL = "CUSTOMER_DELETE_FAIL";

//Message
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";